# Generated by Django 4.2.7 on 2026-02-18 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('system_type', models.CharField(choices=[('ehr', 'Electronic Health Record'), ('hie', 'Health Information Exchange'), ('laboratory', 'Laboratory System'), ('imaging', 'Medical Imaging System'), ('pharmacy', 'Pharmacy Management System'), ('billing', 'Healthcare Billing System'), ('registry', 'Clinical Registry'), ('pacs', 'Picture Archiving System'), ('his', 'Hospital Information System'), ('other', 'Other Healthcare System')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('base_url', models.URLField(help_text='Base URL for FHIR API endpoint')),
                ('fhir_version', models.CharField(choices=[('dstu2', 'FHIR DSTU2'), ('stu3', 'FHIR STU3'), ('r4', 'FHIR R4'), ('r5', 'FHIR R5')], default='r4', max_length=20)),
                ('auth_type', models.CharField(choices=[('none', 'No Authentication'), ('basic', 'Basic Authentication'), ('oauth2', 'OAuth 2.0'), ('client_credentials', 'Client Credentials'), ('bearer_token', 'Bearer Token'), ('mutual_tls', 'Mutual TLS')], default='none', max_length=20)),
                ('auth_config', models.JSONField(blank=True, default=dict, help_text='Authentication configuration (client_id, secrets, etc.)')),
                ('supported_resources', models.JSONField(blank=True, default=list, help_text='List of supported FHIR resource types')),
                ('supported_operations', models.JSONField(blank=True, default=list, help_text='List of supported FHIR operations (read, create, update, delete, search)')),
                ('supports_hl7', models.BooleanField(default=False)),
                ('hl7_version', models.CharField(blank=True, help_text='e.g., 2.5, 2.8', max_length=10)),
                ('hl7_endpoint', models.URLField(blank=True, help_text='HL7 MLLP endpoint')),
                ('is_active', models.BooleanField(default=True)),
                ('last_successful_connection', models.DateTimeField(blank=True, null=True)),
                ('connection_status', models.CharField(choices=[('unknown', 'Unknown'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Connection Error')], default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interop_external_system',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FHIRResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('resource_type', models.CharField(choices=[('Patient', 'Patient'), ('Practitioner', 'Practitioner'), ('Organization', 'Organization'), ('Encounter', 'Encounter'), ('Observation', 'Observation'), ('Condition', 'Condition'), ('Procedure', 'Procedure'), ('MedicationRequest', 'Medication Request'), ('DiagnosticReport', 'Diagnostic Report'), ('AllergyIntolerance', 'Allergy Intolerance'), ('Immunization', 'Immunization'), ('DocumentReference', 'Document Reference'), ('CarePlan', 'Care Plan'), ('Goal', 'Goal'), ('Appointment', 'Appointment'), ('Schedule', 'Schedule'), ('Slot', 'Slot')], max_length=50)),
                ('version_id', models.CharField(default='1', max_length=50)),
                ('resource_data', models.JSONField(help_text='Complete FHIR resource as JSON')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('related_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fhir_resources', to=settings.AUTH_USER_MODEL)),
                ('source_system', models.ForeignKey(blank=True, help_text='System that provided this resource', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fhir_resources', to='interoperability.externalsystem')),
            ],
            options={
                'db_table': 'interop_fhir_resource',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='HL7Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('control_id', models.CharField(help_text='HL7 Message Control ID', max_length=50)),
                ('message_type', models.CharField(choices=[('ADT', 'Admit/Discharge/Transfer'), ('ORM', 'Order Message'), ('ORU', 'Observation Result'), ('SIU', 'Scheduling Information'), ('DFT', 'Detailed Financial Transaction'), ('BAR', 'Billing Account Record'), ('MDM', 'Medical Document Management'), ('QBP', 'Query by Parameter'), ('ACK', 'Acknowledgment'), ('OTHER', 'Other Message Type')], max_length=10)),
                ('trigger_event', models.CharField(help_text='e.g., A01, A03, R01', max_length=10)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('raw_message', models.TextField(help_text='Raw HL7 message')),
                ('parsed_message', models.JSONField(blank=True, default=dict, help_text='Parsed HL7 message as JSON')),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('processed', 'Successfully Processed'), ('error', 'Processing Error'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('processing_errors', models.JSONField(blank=True, default=list)),
                ('processing_log', models.JSONField(blank=True, default=list)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_hl7_messages', to='interoperability.externalsystem')),
                ('related_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hl7_messages', to=settings.AUTH_USER_MODEL)),
                ('source_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hl7_messages', to='interoperability.externalsystem')),
            ],
            options={
                'db_table': 'interop_hl7_message',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='DataMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mapping_type', models.CharField(choices=[('fhir_resource', 'FHIR Resource Mapping'), ('hl7_segment', 'HL7 Segment Mapping'), ('custom_api', 'Custom API Mapping'), ('database_table', 'Database Table Mapping')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('source_format', models.CharField(help_text='Source data format', max_length=100)),
                ('source_schema', models.JSONField(blank=True, default=dict, help_text='Source data schema definition')),
                ('target_format', models.CharField(help_text='Target data format', max_length=100)),
                ('target_schema', models.JSONField(blank=True, default=dict, help_text='Target data schema definition')),
                ('mapping_rules', models.JSONField(default=dict, help_text='Field mapping rules and transformations')),
                ('transformation_code', models.TextField(blank=True, help_text='Custom transformation code (Python)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('test_results', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_mappings', to='interoperability.externalsystem')),
                ('target_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_mappings', to='interoperability.externalsystem')),
            ],
            options={
                'db_table': 'interop_data_mapping',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConsentManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('treatment', 'Treatment'), ('payment', 'Payment'), ('operations', 'Healthcare Operations'), ('research', 'Research'), ('marketing', 'Marketing'), ('directory', 'Directory Listing'), ('emergency', 'Emergency Contact'), ('hie', 'Health Information Exchange'), ('data_sharing', 'External Data Sharing')], max_length=20)),
                ('status', models.CharField(choices=[('granted', 'Consent Granted'), ('denied', 'Consent Denied'), ('withdrawn', 'Consent Withdrawn'), ('expired', 'Consent Expired'), ('pending', 'Consent Pending')], default='pending', max_length=20)),
                ('purpose', models.TextField(help_text='Purpose of data use')),
                ('scope', models.JSONField(default=list, help_text='Scope of data covered by consent (resource types, date ranges, etc.)')),
                ('authorized_purposes', models.JSONField(blank=True, default=list, help_text='Specific purposes for which data can be used')),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_reason', models.TextField(blank=True)),
                ('legal_basis', models.CharField(blank=True, help_text='Legal basis for processing (GDPR Article 6)', max_length=100)),
                ('consent_document', models.TextField(blank=True, help_text='Original consent document text')),
                ('signature_data', models.JSONField(blank=True, default=dict, help_text='Digital signature or consent capture data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_systems', models.ManyToManyField(blank=True, help_text='External systems authorized to access data', to='interoperability.externalsystem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_consents', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interop_consent_management',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('fhir_read', 'FHIR Resource Read'), ('fhir_create', 'FHIR Resource Create'), ('fhir_update', 'FHIR Resource Update'), ('fhir_delete', 'FHIR Resource Delete'), ('fhir_search', 'FHIR Resource Search'), ('hl7_send', 'HL7 Message Send'), ('hl7_receive', 'HL7 Message Receive'), ('data_sync', 'Data Synchronization'), ('bulk_export', 'Bulk Data Export'), ('bulk_import', 'Bulk Data Import')], max_length=20)),
                ('endpoint_url', models.URLField(help_text='Specific endpoint called')),
                ('http_method', models.CharField(default='GET', max_length=10)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout')], default='initiated', max_length=20)),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP status code', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Duration in milliseconds', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('external_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='interoperability.externalsystem')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_fhir_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='interoperability.fhirresource')),
                ('related_hl7_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='interoperability.hl7message')),
                ('related_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interop_integration_transaction',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['transaction_type', 'status'], name='interop_int_transac_475f9a_idx'), models.Index(fields=['external_system', 'started_at'], name='interop_int_externa_0e63a6_idx'), models.Index(fields=['status', 'started_at'], name='interop_int_status_c5e031_idx'), models.Index(fields=['related_patient'], name='interop_int_related_fe3f34_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='hl7message',
            index=models.Index(fields=['message_type', 'status'], name='interop_hl7_message_a05a62_idx'),
        ),
        migrations.AddIndex(
            model_name='hl7message',
            index=models.Index(fields=['direction', 'received_at'], name='interop_hl7_directi_e110d5_idx'),
        ),
        migrations.AddIndex(
            model_name='hl7message',
            index=models.Index(fields=['related_patient'], name='interop_hl7_related_cc4ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='hl7message',
            index=models.Index(fields=['control_id'], name='interop_hl7_control_5ba638_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirresource',
            index=models.Index(fields=['resource_type', 'last_updated'], name='interop_fhi_resourc_a12f7c_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirresource',
            index=models.Index(fields=['related_patient'], name='interop_fhi_related_d0e445_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirresource',
            index=models.Index(fields=['source_system'], name='interop_fhi_source__737aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirresource',
            index=models.Index(fields=['resource_id'], name='interop_fhi_resourc_021715_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fhirresource',
            unique_together={('resource_id', 'version_id')},
        ),
        migrations.AddIndex(
            model_name='externalsystem',
            index=models.Index(fields=['system_type', 'is_active'], name='interop_ext_system__6e3ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='externalsystem',
            index=models.Index(fields=['fhir_version'], name='interop_ext_fhir_ve_d79ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='externalsystem',
            index=models.Index(fields=['connection_status'], name='interop_ext_connect_41b211_idx'),
        ),
        migrations.AddIndex(
            model_name='datamapping',
            index=models.Index(fields=['mapping_type', 'is_active'], name='interop_dat_mapping_44e943_idx'),
        ),
        migrations.AddIndex(
            model_name='datamapping',
            index=models.Index(fields=['source_system'], name='interop_dat_source__2b9e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='datamapping',
            index=models.Index(fields=['target_system'], name='interop_dat_target__ff428c_idx'),
        ),
        migrations.AddIndex(
            model_name='consentmanagement',
            index=models.Index(fields=['patient', 'consent_type'], name='interop_con_patient_d70658_idx'),
        ),
        migrations.AddIndex(
            model_name='consentmanagement',
            index=models.Index(fields=['status', 'expires_at'], name='interop_con_status_878e72_idx'),
        ),
        migrations.AddIndex(
            model_name='consentmanagement',
            index=models.Index(fields=['granted_at'], name='interop_con_granted_281d01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='consentmanagement',
            unique_together={('patient', 'consent_type')},
        ),
    ]
