# Generated by Django 4.2.28 on 2026-02-16 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('consultation', 'Consultation'), ('diagnosis', 'Diagnosis'), ('lab_result', 'Lab Result'), ('imaging', 'Imaging Report'), ('procedure', 'Procedure Note'), ('progress', 'Progress Note'), ('discharge', 'Discharge Summary'), ('other', 'Other')], default='consultation', help_text='Type of medical record', max_length=20)),
                ('title', models.CharField(help_text='Record title or summary', max_length=200)),
                ('description', models.TextField(help_text='Detailed description or notes')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', help_text='Severity or priority level', max_length=20)),
                ('diagnosis_code', models.CharField(blank=True, help_text='ICD-10 diagnosis code (if applicable)', max_length=20)),
                ('attachments', models.FileField(blank=True, help_text='Attached files (lab reports, images, etc.)', null=True, upload_to='medical_records/')),
                ('is_confidential', models.BooleanField(default=False, help_text='Mark as confidential (restricted access)')),
                ('ai_risk_score', models.FloatField(blank=True, help_text='AI-predicted risk score (0-100)', null=True)),
                ('ai_recommendations', models.TextField(blank=True, help_text='AI-generated recommendations')),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of the medical event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Healthcare provider who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient this record belongs to', limit_choices_to={'role__name': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='VitalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature in Celsius', max_digits=4, null=True)),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, help_text='Systolic blood pressure (mmHg)', null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, help_text='Diastolic blood pressure (mmHg)', null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, help_text='Heart rate (beats per minute)', null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, help_text='Respiratory rate (breaths per minute)', null=True)),
                ('oxygen_saturation', models.PositiveIntegerField(blank=True, help_text='Blood oxygen saturation (%)', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=5, null=True)),
                ('blood_glucose', models.PositiveIntegerField(blank=True, help_text='Blood glucose level (mg/dL)', null=True)),
                ('pain_level', models.PositiveIntegerField(blank=True, help_text='Pain level (0-10 scale)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional observations or notes')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when vitals were recorded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(help_text='Patient whose vitals are recorded', limit_choices_to={'role__name': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='vital_records', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(help_text='Staff member who recorded the vitals', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vital Record',
                'verbose_name_plural': 'Vital Records',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Treatment plan title', max_length=200)),
                ('description', models.TextField(help_text='Detailed treatment description')),
                ('diagnosis', models.TextField(help_text='Primary diagnosis for this treatment')),
                ('medications', models.TextField(blank=True, help_text='Prescribed medications (name, dosage, frequency)')),
                ('procedures', models.TextField(blank=True, help_text='Scheduled procedures or interventions')),
                ('lifestyle_recommendations', models.TextField(blank=True, help_text='Diet, exercise, and lifestyle recommendations')),
                ('follow_up_instructions', models.TextField(blank=True, help_text='Follow-up care instructions')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='draft', help_text='Current status of the treatment plan', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='Treatment start date')),
                ('end_date', models.DateField(blank=True, help_text='Expected treatment end date', null=True)),
                ('next_review_date', models.DateField(blank=True, help_text='Next review/follow-up date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Doctor who created this plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
                ('medical_record', models.ForeignKey(blank=True, help_text='Associated medical record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plans', to='clinical_portal.medicalrecord')),
                ('patient', models.ForeignKey(help_text='Patient for this treatment plan', limit_choices_to={'role__name': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Treatment Plan',
                'verbose_name_plural': 'Treatment Plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
