# Generated by Django 4.2.7 on 2026-02-18 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(help_text='Base32 encoded secret key for TOTP', max_length=32)),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether 2FA is currently enabled for this user')),
                ('backup_codes', models.JSONField(default=list, help_text='List of backup codes for account recovery')),
                ('qr_code', models.ImageField(blank=True, help_text='QR code image for initial setup', null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User associated with this 2FA setup', on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Two Factor Authentication',
                'verbose_name_plural': 'Two Factor Authentications',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('CREATE', 'Record Created'), ('READ', 'Record Accessed'), ('UPDATE', 'Record Modified'), ('DELETE', 'Record Deleted'), ('EXPORT', 'Data Exported'), ('PRINT', 'Data Printed'), ('SHARE', 'Data Shared'), ('2FA_ENABLE', '2FA Enabled'), ('2FA_DISABLE', '2FA Disabled'), ('PASSWORD_CHANGE', 'Password Changed'), ('FAILED_LOGIN', 'Failed Login Attempt')], help_text='Type of action performed', max_length=20)),
                ('resource_type', models.CharField(blank=True, help_text='Type of resource accessed (e.g., Patient, Appointment)', max_length=50)),
                ('resource_id', models.CharField(blank=True, help_text='ID of the specific resource accessed', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which action was performed', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request')),
                ('success', models.BooleanField(default=True, help_text='Whether the action was successful')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='users_audit_user_id_29b33e_idx'), models.Index(fields=['action', '-timestamp'], name='users_audit_action_e79129_idx'), models.Index(fields=['resource_type', 'resource_id'], name='users_audit_resourc_156f16_idx')],
            },
        ),
    ]
