# Generated by Django 4.2.28 on 2026-02-16 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_record_number', models.CharField(blank=True, help_text='Hospital medical record number', max_length=50, null=True, unique=True)),
                ('insurance_type', models.CharField(choices=[('private', 'Private Insurance'), ('public', 'Public Insurance'), ('medicare', 'Medicare'), ('medicaid', 'Medicaid'), ('none', 'No Insurance'), ('other', 'Other')], default='none', help_text='Type of health insurance', max_length=20)),
                ('insurance_provider', models.CharField(blank=True, help_text='Insurance company name', max_length=100)),
                ('insurance_policy_number', models.CharField(blank=True, help_text='Insurance policy number', max_length=50)),
                ('preferred_pharmacy', models.CharField(blank=True, help_text='Preferred pharmacy for prescriptions', max_length=200)),
                ('communication_preference', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('portal', 'Patient Portal')], default='email', help_text='Preferred communication method', max_length=20)),
                ('consent_to_research', models.BooleanField(default=False, help_text='Consent to use data for research')),
                ('consent_to_marketing', models.BooleanField(default=False, help_text='Consent to receive marketing communications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_doctor', models.ForeignKey(blank=True, help_text='Primary care physician', limit_choices_to={'role__name': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_patients', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='The patient user account', on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Profile',
                'verbose_name_plural': 'Patient Profiles',
            },
        ),
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('weight', 'Weight (kg)'), ('blood_pressure', 'Blood Pressure'), ('heart_rate', 'Heart Rate (bpm)'), ('blood_glucose', 'Blood Glucose (mg/dL)'), ('temperature', 'Temperature (°C)'), ('steps', 'Steps'), ('sleep_hours', 'Sleep Hours'), ('water_intake', 'Water Intake (L)'), ('mood', 'Mood (1-10)'), ('pain_level', 'Pain Level (1-10)'), ('exercise_minutes', 'Exercise (minutes)'), ('calories', 'Calories Consumed'), ('other', 'Other')], help_text='Type of health metric', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Metric value', max_digits=10)),
                ('secondary_value', models.DecimalField(blank=True, decimal_places=2, help_text='Secondary value (e.g., diastolic for blood pressure)', max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the metric was recorded')),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('device', 'Connected Device'), ('imported', 'Imported')], default='manual', help_text='How the metric was recorded', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(help_text='Patient recording the metric', limit_choices_to={'role__name': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Metric',
                'verbose_name_plural': 'Health Metrics',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('consultation', 'Consultation'), ('follow_up', 'Follow-up'), ('checkup', 'Regular Checkup'), ('vaccination', 'Vaccination'), ('lab_test', 'Lab Test'), ('imaging', 'Imaging/Scan'), ('procedure', 'Procedure'), ('emergency', 'Emergency'), ('telemedicine', 'Telemedicine'), ('other', 'Other')], default='consultation', help_text='Type of appointment', max_length=20)),
                ('appointment_date', models.DateField(help_text='Date of appointment')),
                ('appointment_time', models.TimeField(help_text='Time of appointment')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Expected duration in minutes')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='scheduled', help_text='Appointment status', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for the appointment')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('location', models.CharField(blank=True, help_text='Appointment location (room, department)', max_length=100)),
                ('is_telemedicine', models.BooleanField(default=False, help_text='Whether this is a telemedicine appointment')),
                ('meeting_link', models.URLField(blank=True, help_text='Video call link for telemedicine')),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether reminder has been sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(help_text='Doctor for the appointment', limit_choices_to={'role__name': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient booking the appointment', limit_choices_to={'role__name': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
    ]
