# Generated by Django 4.2.7 on 2026-02-18 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(help_text='Doctor for the appointment', limit_choices_to={'role__name': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_portal_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(help_text='Patient booking the appointment', limit_choices_to={'role__name': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_portal_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
