# Generated by Django 4.2.7 on 2026-02-18 18:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Model name', max_length=200)),
                ('model_type', models.CharField(choices=[('patient_flow', 'Patient Flow Prediction'), ('bed_occupancy', 'Bed Occupancy Forecasting'), ('resource_demand', 'Resource Demand Prediction'), ('readmission_risk', 'Readmission Risk Assessment'), ('length_of_stay', 'Length of Stay Prediction'), ('clinical_outcome', 'Clinical Outcome Prediction'), ('cost_prediction', 'Cost and Financial Forecasting'), ('staff_optimization', 'Staff Allocation Optimization'), ('equipment_maintenance', 'Equipment Maintenance Prediction'), ('supply_chain', 'Supply Chain Optimization')], max_length=50)),
                ('algorithm', models.CharField(choices=[('linear_regression', 'Linear Regression'), ('random_forest', 'Random Forest'), ('gradient_boosting', 'Gradient Boosting'), ('neural_network', 'Neural Network'), ('time_series', 'Time Series (ARIMA/LSTM)'), ('clustering', 'Clustering (K-Means)'), ('classification', 'Classification (SVM/Logistic)'), ('ensemble', 'Ensemble Methods')], max_length=50)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('accuracy', models.FloatField(blank=True, help_text='Model accuracy (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('precision', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('recall', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('f1_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Model hyperparameters and configuration')),
                ('training_data_summary', models.JSONField(blank=True, default=dict, help_text='Summary of training data used')),
                ('is_active', models.BooleanField(default=True)),
                ('is_production_ready', models.BooleanField(default=False)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('last_retrained', models.DateTimeField(blank=True, null=True)),
                ('next_retrain_due', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_predictive_model',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientFlowPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('prediction_horizon', models.CharField(choices=[('1_hour', '1 Hour'), ('4_hours', '4 Hours'), ('12_hours', '12 Hours'), ('24_hours', '24 Hours'), ('48_hours', '48 Hours'), ('7_days', '7 Days'), ('30_days', '30 Days')], max_length=20)),
                ('target_date', models.DateTimeField(help_text='Date/time for which prediction is made')),
                ('department', models.CharField(choices=[('emergency', 'Emergency Department'), ('icu', 'Intensive Care Unit'), ('general_ward', 'General Ward'), ('surgery', 'Surgery'), ('maternity', 'Maternity'), ('pediatrics', 'Pediatrics'), ('cardiology', 'Cardiology'), ('oncology', 'Oncology'), ('outpatient', 'Outpatient Clinic')], max_length=50)),
                ('predicted_admissions', models.PositiveIntegerField(default=0)),
                ('predicted_discharges', models.PositiveIntegerField(default=0)),
                ('predicted_bed_occupancy', models.PositiveIntegerField(default=0)),
                ('predicted_capacity_utilization', models.FloatField(help_text='Capacity utilization ratio (0-2, >1 indicates overcapacity)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('confidence_score', models.FloatField(help_text='Model confidence in prediction (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('prediction_interval_lower', models.FloatField(blank=True, null=True)),
                ('prediction_interval_upper', models.FloatField(blank=True, null=True)),
                ('predicted_staff_needed', models.JSONField(blank=True, default=dict, help_text='Predicted staffing needs by role')),
                ('predicted_resource_demand', models.JSONField(blank=True, default=dict, help_text='Predicted resource requirements')),
                ('actual_admissions', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_discharges', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_bed_occupancy', models.PositiveIntegerField(blank=True, null=True)),
                ('prediction_error', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_predictions', to='analytics.predictivemodel')),
            ],
            options={
                'db_table': 'analytics_patient_flow_prediction',
                'ordering': ['-prediction_date', 'target_date'],
            },
        ),
        migrations.CreateModel(
            name='DataQualityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(help_text='Source system or table', max_length=100)),
                ('metric_type', models.CharField(choices=[('completeness', 'Data Completeness'), ('accuracy', 'Data Accuracy'), ('consistency', 'Data Consistency'), ('timeliness', 'Data Timeliness'), ('validity', 'Data Validity'), ('uniqueness', 'Data Uniqueness')], max_length=20)),
                ('score', models.FloatField(help_text='Quality score (0-1, higher is better)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('threshold', models.FloatField(default=0.95, help_text='Quality threshold for alerting', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('passed_records', models.PositiveIntegerField(default=0)),
                ('failed_records', models.PositiveIntegerField(default=0)),
                ('metric_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('issues_identified', models.JSONField(blank=True, default=list)),
                ('alert_triggered', models.BooleanField(default=False)),
                ('alert_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_data_quality_metric',
                'ordering': ['-metric_date'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalOutcomePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_type', models.CharField(choices=[('mortality_risk', 'Mortality Risk'), ('readmission_risk', 'Readmission Risk'), ('complication_risk', 'Complication Risk'), ('length_of_stay', 'Length of Stay'), ('icu_admission', 'ICU Admission Risk'), ('surgery_outcome', 'Surgical Outcome'), ('medication_response', 'Medication Response'), ('infection_risk', 'Healthcare-Associated Infection Risk')], max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], max_length=20)),
                ('risk_score', models.FloatField(help_text='Risk score (0-1, higher is riskier)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('predicted_date', models.DateTimeField(blank=True, null=True)),
                ('prediction_horizon_days', models.PositiveIntegerField(default=30, help_text='Prediction horizon in days')),
                ('risk_factors', models.JSONField(blank=True, default=list, help_text='Key risk factors identified by the model')),
                ('protective_factors', models.JSONField(blank=True, default=list, help_text='Protective factors that reduce risk')),
                ('diagnosis_codes', models.JSONField(blank=True, default=list)),
                ('current_medications', models.JSONField(blank=True, default=list)),
                ('vital_signs_at_prediction', models.JSONField(blank=True, default=dict)),
                ('lab_values_at_prediction', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.FloatField(help_text='Model confidence in prediction', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('explanation', models.TextField(blank=True, help_text='Human-readable explanation')),
                ('recommended_interventions', models.JSONField(blank=True, default=list, help_text='Recommended clinical interventions')),
                ('monitoring_recommendations', models.JSONField(blank=True, default=list, help_text='Recommended monitoring protocols')),
                ('actual_outcome', models.BooleanField(blank=True, null=True)),
                ('actual_outcome_date', models.DateTimeField(blank=True, null=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_outcome_predictions', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_predictions', to='analytics.predictivemodel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_clinical_outcome_prediction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('patient_flow', 'Patient Flow Analytics'), ('resource_utilization', 'Resource Utilization Report'), ('clinical_outcomes', 'Clinical Outcomes Analysis'), ('financial_analytics', 'Financial Performance Report'), ('quality_metrics', 'Quality Metrics Dashboard'), ('operational_kpis', 'Operational KPIs'), ('predictive_insights', 'Predictive Analytics Insights'), ('department_performance', 'Department Performance Report')], max_length=50)),
                ('frequency', models.CharField(choices=[('real_time', 'Real-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('ad_hoc', 'Ad-hoc')], max_length=20)),
                ('data', models.JSONField(default=dict, help_text='Report data and metrics')),
                ('charts', models.JSONField(blank=True, default=list, help_text='Chart configurations')),
                ('kpis', models.JSONField(blank=True, default=dict, help_text='Key performance indicators')),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed'), ('archived', 'Archived')], default='completed', max_length=20)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, help_text='Users who have access to this report', related_name='accessible_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_report',
                'ordering': ['-report_date'],
            },
        ),
        migrations.AddIndex(
            model_name='predictivemodel',
            index=models.Index(fields=['model_type', 'is_active'], name='analytics_p_model_t_8ed1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='predictivemodel',
            index=models.Index(fields=['is_production_ready'], name='analytics_p_is_prod_00605c_idx'),
        ),
        migrations.AddIndex(
            model_name='predictivemodel',
            index=models.Index(fields=['next_retrain_due'], name='analytics_p_next_re_be0158_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='predictivemodel',
            unique_together={('name', 'version')},
        ),
        migrations.AddIndex(
            model_name='patientflowprediction',
            index=models.Index(fields=['department', 'target_date'], name='analytics_p_departm_2a258b_idx'),
        ),
        migrations.AddIndex(
            model_name='patientflowprediction',
            index=models.Index(fields=['prediction_horizon', 'prediction_date'], name='analytics_p_predict_5c661a_idx'),
        ),
        migrations.AddIndex(
            model_name='patientflowprediction',
            index=models.Index(fields=['target_date'], name='analytics_p_target__51707e_idx'),
        ),
        migrations.AddIndex(
            model_name='dataqualitymetric',
            index=models.Index(fields=['data_source', 'metric_type'], name='analytics_d_data_so_caffaa_idx'),
        ),
        migrations.AddIndex(
            model_name='dataqualitymetric',
            index=models.Index(fields=['alert_triggered', 'alert_acknowledged'], name='analytics_d_alert_t_8fc20d_idx'),
        ),
        migrations.AddIndex(
            model_name='dataqualitymetric',
            index=models.Index(fields=['metric_date'], name='analytics_d_metric__564120_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicaloutcomeprediction',
            index=models.Index(fields=['patient', 'outcome_type'], name='analytics_c_patient_b47b60_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicaloutcomeprediction',
            index=models.Index(fields=['risk_level', 'created_at'], name='analytics_c_risk_le_77256b_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicaloutcomeprediction',
            index=models.Index(fields=['predicted_date'], name='analytics_c_predict_cffed3_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicaloutcomeprediction',
            index=models.Index(fields=['outcome_type', 'risk_score'], name='analytics_c_outcome_09775c_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['report_type', 'report_date'], name='analytics_r_report__bb7d36_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['frequency', 'is_scheduled'], name='analytics_r_frequen_a13e75_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['status'], name='analytics_r_status_030016_idx'),
        ),
    ]
