# Generated by Django 4.2.7 on 2026-02-18 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('consultation', 'Consultation'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency'), ('telemedicine', 'Telemedicine'), ('routine_checkup', 'Routine Checkup'), ('specialist', 'Specialist Visit')], help_text='Type of appointment', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the appointment type')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Default duration in minutes')),
                ('color_code', models.CharField(default='#007bff', help_text='Color code for calendar display (hex format)', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this appointment type is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appointment Type',
                'verbose_name_plural': 'Appointment Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(help_text='Date of the appointment')),
                ('scheduled_time', models.TimeField(help_text='Time of the appointment')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration of appointment in minutes')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='requested', help_text='Current status of the appointment', max_length=20)),
                ('reason', models.TextField(help_text='Reason for the appointment')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the appointment')),
                ('doctor_notes', models.TextField(blank=True, help_text='Doctor notes after the appointment')),
                ('is_telemedicine', models.BooleanField(default=False, help_text='Whether this is a telemedicine appointment')),
                ('video_room_id', models.CharField(blank=True, help_text='Video room ID for telemedicine appointments', max_length=100)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the appointment was cancelled', null=True)),
                ('send_reminder', models.BooleanField(default=True, help_text='Whether to send appointment reminders')),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether reminder has been sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_type', models.ForeignKey(help_text='Type of appointment', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.appointmenttype')),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='User who cancelled the appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_cancelled_by_user', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(help_text='Doctor for this appointment', limit_choices_to={'role__name': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient for this appointment', limit_choices_to={'role__name': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week (0=Monday, 6=Sunday)')),
                ('start_time', models.TimeField(help_text='Start time for availability')),
                ('end_time', models.TimeField(help_text='End time for availability')),
                ('break_start_time', models.TimeField(blank=True, help_text='Break start time (optional)', null=True)),
                ('break_end_time', models.TimeField(blank=True, help_text='Break end time (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schedule is currently active')),
                ('max_appointments', models.PositiveIntegerField(default=20, help_text='Maximum appointments allowed per day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(help_text='Doctor this schedule belongs to', limit_choices_to={'role__name': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Schedule',
                'verbose_name_plural': 'Doctor Schedules',
                'ordering': ['doctor', 'day_of_week', 'start_time'],
                'unique_together': {('doctor', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], help_text='Type of reminder', max_length=10)),
                ('scheduled_time', models.DateTimeField(help_text='When the reminder should be sent')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the reminder was actually sent', null=True)),
                ('is_sent', models.BooleanField(default=False, help_text='Whether the reminder has been sent')),
                ('delivery_status', models.CharField(blank=True, help_text='Delivery status (delivered, failed, etc.)', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if delivery failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(help_text='Appointment this reminder is for', on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'Appointment Reminder',
                'verbose_name_plural': 'Appointment Reminders',
                'ordering': ['scheduled_time'],
                'unique_together': {('appointment', 'reminder_type', 'scheduled_time')},
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', '-scheduled_date'], name='appointment_patient_3fbb56_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', '-scheduled_date'], name='appointment_doctor__ad345d_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', '-scheduled_date'], name='appointment_status_5f27d6_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['scheduled_date', 'scheduled_time'], name='appointment_schedul_59e8bc_idx'),
        ),
    ]
