# Generated by Django 4.2.7 on 2026-02-18 16:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_class', models.CharField(blank=True, help_text='If allergy to entire drug class', max_length=100)),
                ('reaction_type', models.CharField(choices=[('allergic', 'Allergic Reaction'), ('intolerance', 'Drug Intolerance'), ('adverse_effect', 'Adverse Effect'), ('contraindication', 'Contraindication')], default='allergic', max_length=20)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life Threatening')], max_length=20)),
                ('symptoms', models.TextField(help_text='Description of allergic reaction symptoms')),
                ('date_identified', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'prescriptions_drug_allergy',
            },
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_level', models.CharField(choices=[('contraindicated', 'Contraindicated'), ('major', 'Major'), ('moderate', 'Moderate'), ('minor', 'Minor')], max_length=20)),
                ('interaction_type', models.CharField(help_text='e.g., Pharmacokinetic, Pharmacodynamic', max_length=100)),
                ('clinical_effects', models.TextField(help_text='Description of interaction effects')),
                ('mechanism', models.TextField(blank=True, help_text='Mechanism of interaction')),
                ('management_strategy', models.TextField(blank=True, help_text='How to manage the interaction')),
                ('evidence_level', models.CharField(choices=[('established', 'Established'), ('probable', 'Probable'), ('suspected', 'Suspected'), ('possible', 'Possible'), ('unlikely', 'Unlikely')], default='probable', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, help_text='Data source', max_length=100)),
                ('last_reviewed', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'prescriptions_drug_interaction',
            },
        ),
        migrations.CreateModel(
            name='MedicationDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndc_code', models.CharField(help_text='National Drug Code', max_length=12, unique=True)),
                ('rxnorm_code', models.CharField(blank=True, help_text='RxNorm Concept ID', max_length=20, null=True)),
                ('generic_name', models.CharField(db_index=True, max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('strength', models.CharField(help_text="e.g., '500mg', '10mg/5ml'", max_length=100)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('liquid', 'Liquid'), ('injection', 'Injection'), ('topical', 'Topical'), ('inhaler', 'Inhaler'), ('patch', 'Patch'), ('suppository', 'Suppository'), ('drops', 'Drops'), ('cream', 'Cream'), ('ointment', 'Ointment'), ('spray', 'Spray')], max_length=20)),
                ('route_of_administration', models.CharField(default='oral', max_length=50)),
                ('drug_class', models.CharField(choices=[('antibiotic', 'Antibiotic'), ('analgesic', 'Pain Reliever'), ('antihypertensive', 'Blood Pressure'), ('anticoagulant', 'Blood Thinner'), ('antidiabetic', 'Diabetes'), ('antidepressant', 'Antidepressant'), ('antihistamine', 'Allergy'), ('bronchodilator', 'Respiratory'), ('diuretic', 'Diuretic'), ('steroid', 'Corticosteroid'), ('vitamin', 'Vitamin/Supplement'), ('other', 'Other')], max_length=30)),
                ('controlled_substance_schedule', models.CharField(blank=True, help_text='DEA schedule: CI, CII, CIII, CIV, CV', max_length=5, null=True)),
                ('therapeutic_class', models.CharField(blank=True, max_length=100)),
                ('pharmacologic_class', models.CharField(blank=True, max_length=100)),
                ('fda_approved', models.BooleanField(default=True)),
                ('requires_prescription', models.BooleanField(default=True)),
                ('otc_available', models.BooleanField(default=False, help_text='Over-the-counter available')),
                ('black_box_warning', models.BooleanField(default=False)),
                ('pregnancy_category', models.CharField(blank=True, help_text='A, B, C, D, X', max_length=5)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medication Database',
                'db_table': 'prescriptions_medication_database',
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pharmacy_type', models.CharField(choices=[('retail', 'Retail Pharmacy'), ('hospital', 'Hospital Pharmacy'), ('mail_order', 'Mail Order'), ('specialty', 'Specialty Pharmacy'), ('compounding', 'Compounding Pharmacy')], default='retail', max_length=20)),
                ('ncpdp_id', models.CharField(help_text='NCPDP Provider ID', max_length=7, unique=True)),
                ('npi_number', models.CharField(blank=True, help_text='National Provider Identifier', max_length=10)),
                ('dea_number', models.CharField(blank=True, help_text='DEA Registration Number', max_length=15)),
                ('phone', models.CharField(max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('hours_of_operation', models.JSONField(blank=True, default=dict)),
                ('accepts_electronic_prescriptions', models.BooleanField(default=True)),
                ('supports_controlled_substances', models.BooleanField(default=True)),
                ('is_preferred_network', models.BooleanField(default=False)),
                ('insurance_networks', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pharmacies',
                'db_table': 'prescriptions_pharmacy',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rx_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('dosage_instructions', models.TextField(help_text='Complete dosing instructions')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity to dispense')),
                ('days_supply', models.PositiveIntegerField(help_text='Expected days of therapy')),
                ('refills_authorized', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('refills_used', models.PositiveIntegerField(default=0)),
                ('diagnosis_code', models.CharField(blank=True, help_text='ICD-10 code', max_length=20)),
                ('diagnosis_description', models.CharField(blank=True, max_length=200)),
                ('indication', models.TextField(blank=True, help_text='Reason for prescribing')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('transmitted', 'Transmitted to Pharmacy'), ('filled', 'Filled by Pharmacy'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('denied', 'Denied')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT (Immediate)')], default='routine', max_length=20)),
                ('date_prescribed', models.DateTimeField(auto_now_add=True)),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateTimeField()),
                ('last_filled_date', models.DateTimeField(blank=True, null=True)),
                ('transmitted_at', models.DateTimeField(blank=True, null=True)),
                ('allergy_checked', models.BooleanField(default=False)),
                ('interaction_checked', models.BooleanField(default=False)),
                ('duplicate_therapy_checked', models.BooleanField(default=False)),
                ('electronically_signed', models.BooleanField(default=False)),
                ('signature_timestamp', models.DateTimeField(blank=True, null=True)),
                ('pharmacy_notes', models.TextField(blank=True, help_text='Notes for pharmacist')),
                ('patient_instructions', models.TextField(blank=True, help_text='Patient counseling notes')),
                ('prescriber_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.medicationdatabase')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescriptions.pharmacy')),
                ('prescriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prescriptions_prescription',
                'ordering': ['-date_prescribed'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionRefill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refill_number', models.PositiveIntegerField()),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('request_method', models.CharField(choices=[('patient', 'Patient Request'), ('pharmacy', 'Pharmacy Request'), ('automatic', 'Automatic Refill'), ('provider', 'Provider Initiated')], default='patient', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Refill Requested'), ('approved', 'Approved by Doctor'), ('denied', 'Denied'), ('transmitted', 'Transmitted to Pharmacy'), ('filled', 'Filled'), ('picked_up', 'Picked Up')], default='requested', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('denial_reason', models.TextField(blank=True)),
                ('filled_date', models.DateTimeField(blank=True, null=True)),
                ('picked_up_date', models.DateTimeField(blank=True, null=True)),
                ('quantity_dispensed', models.PositiveIntegerField(blank=True, null=True)),
                ('days_supply_dispensed', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_refills', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescriptions.pharmacy')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refills', to='prescriptions.prescription')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refill_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prescriptions_prescription_refill',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Prescription Created'), ('modified', 'Prescription Modified'), ('approved', 'Prescription Approved'), ('transmitted', 'Transmitted to Pharmacy'), ('cancelled', 'Prescription Cancelled'), ('refill_requested', 'Refill Requested'), ('refill_approved', 'Refill Approved'), ('filled', 'Prescription Filled'), ('viewed', 'Prescription Viewed'), ('printed', 'Prescription Printed')], max_length=20)),
                ('field_changes', models.JSONField(blank=True, default=dict, help_text='What fields were changed')),
                ('previous_values', models.JSONField(blank=True, default=dict, help_text='Previous field values')),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='New field values')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='prescriptions.prescription')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prescriptions_prescription_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['ncpdp_id'], name='prescriptio_ncpdp_i_bd0469_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['city', 'state'], name='prescriptio_city_a5be67_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['is_active'], name='prescriptio_is_acti_b8269d_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationdatabase',
            index=models.Index(fields=['generic_name'], name='prescriptio_generic_9cfebd_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationdatabase',
            index=models.Index(fields=['brand_name'], name='prescriptio_brand_n_6d8b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationdatabase',
            index=models.Index(fields=['drug_class'], name='prescriptio_drug_cl_b73cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationdatabase',
            index=models.Index(fields=['controlled_substance_schedule'], name='prescriptio_control_dc5f7c_idx'),
        ),
        migrations.AddField(
            model_name='druginteraction',
            name='medication_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_drug1', to='prescriptions.medicationdatabase'),
        ),
        migrations.AddField(
            model_name='druginteraction',
            name='medication_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_drug2', to='prescriptions.medicationdatabase'),
        ),
        migrations.AddField(
            model_name='drugallergy',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prescriptions.medicationdatabase'),
        ),
        migrations.AddField(
            model_name='drugallergy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_allergies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drugallergy',
            name='verified_by_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_allergies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='prescriptionrefill',
            unique_together={('prescription', 'refill_number')},
        ),
        migrations.AddIndex(
            model_name='prescriptionauditlog',
            index=models.Index(fields=['prescription', 'timestamp'], name='prescriptio_prescri_1963ac_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionauditlog',
            index=models.Index(fields=['user', 'timestamp'], name='prescriptio_user_id_01578f_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionauditlog',
            index=models.Index(fields=['action'], name='prescriptio_action_4f8ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'status'], name='prescriptio_patient_283c70_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescriber', 'date_prescribed'], name='prescriptio_prescri_04c60e_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescription_id'], name='prescriptio_prescri_ebd264_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status'], name='prescriptio_status_940ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='druginteraction',
            index=models.Index(fields=['interaction_level'], name='prescriptio_interac_afa965_idx'),
        ),
        migrations.AddIndex(
            model_name='druginteraction',
            index=models.Index(fields=['medication_1', 'medication_2'], name='prescriptio_medicat_16728f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='druginteraction',
            unique_together={('medication_1', 'medication_2')},
        ),
        migrations.AddIndex(
            model_name='drugallergy',
            index=models.Index(fields=['patient', 'is_active'], name='prescriptio_patient_156bc0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='drugallergy',
            unique_together={('patient', 'medication')},
        ),
    ]
