# Generated by Django 4.2.7 on 2026-02-18 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemedicineSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_type', models.CharField(choices=[('video_consultation', 'Video Consultation'), ('phone_consultation', 'Phone Consultation'), ('chat_consultation', 'Chat Consultation'), ('remote_monitoring', 'Remote Monitoring'), ('follow_up', 'Follow-up Session'), ('emergency_consult', 'Emergency Consultation')], default='video_consultation', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('waiting', 'Waiting Room'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('technical_issues', 'Technical Issues')], default='scheduled', max_length=20)),
                ('scheduled_start_time', models.DateTimeField()),
                ('scheduled_end_time', models.DateTimeField()),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('platform', models.CharField(choices=[('webrtc', 'WebRTC'), ('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('webex', 'Cisco Webex'), ('phone', 'Phone Call'), ('custom', 'Custom Platform')], default='webrtc', max_length=50)),
                ('room_url', models.URLField(blank=True, help_text='Virtual room/meeting URL')),
                ('room_id', models.CharField(blank=True, max_length=100)),
                ('meeting_password', models.CharField(blank=True, max_length=50)),
                ('recording_status', models.CharField(choices=[('not_recorded', 'Not Recorded'), ('recording', 'Recording in Progress'), ('recorded', 'Recorded'), ('processing', 'Processing'), ('failed', 'Recording Failed')], default='not_recorded', max_length=20)),
                ('recording_consent', models.BooleanField(default=False, help_text='Patient consent for recording')),
                ('recording_url', models.URLField(blank=True)),
                ('recording_duration', models.PositiveIntegerField(blank=True, help_text='Recording duration in seconds', null=True)),
                ('chief_complaint', models.TextField(blank=True, help_text='Main reason for consultation')),
                ('consultation_notes', models.TextField(blank=True, help_text='Clinical notes from consultation')),
                ('diagnosis', models.TextField(blank=True, help_text='Diagnosis or assessment')),
                ('treatment_plan', models.TextField(blank=True, help_text='Treatment recommendations')),
                ('connection_quality', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('failed', 'Connection Failed')], max_length=20)),
                ('technical_issues', models.TextField(blank=True, help_text='Any technical problems encountered')),
                ('billing_code', models.CharField(blank=True, help_text='CPT code for telemedicine visit', max_length=20)),
                ('insurance_approved', models.BooleanField(default=False)),
                ('copay_collected', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('patient_satisfaction_score', models.PositiveIntegerField(blank=True, help_text='Patient satisfaction rating (1-5)', null=True)),
                ('provider_satisfaction_score', models.PositiveIntegerField(blank=True, help_text='Provider satisfaction rating (1-5)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_participants', models.ManyToManyField(blank=True, help_text='Other healthcare providers, interpreters, or family members', related_name='telemedicine_participants', to=settings.AUTH_USER_MODEL)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telemedicine_session', to='appointments.appointment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_telemedicine_sessions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_telemedicine_sessions', to=settings.AUTH_USER_MODEL)),
                ('prescriptions_issued', models.ManyToManyField(blank=True, related_name='telemedicine_sessions', to='prescriptions.prescription')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_telemedicine_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telemedicine_session',
                'ordering': ['-scheduled_start_time'],
            },
        ),
        migrations.CreateModel(
            name='VirtualWaitingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_joined_at', models.DateTimeField(blank=True, null=True)),
                ('provider_notified_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_wait_time', models.PositiveIntegerField(blank=True, help_text='Estimated wait time in minutes', null=True)),
                ('educational_content_viewed', models.JSONField(blank=True, default=list)),
                ('forms_completed', models.JSONField(blank=True, default=list)),
                ('vital_signs_submitted', models.JSONField(blank=True, default=dict)),
                ('camera_test_passed', models.BooleanField(default=False)),
                ('microphone_test_passed', models.BooleanField(default=False)),
                ('speaker_test_passed', models.BooleanField(default=False)),
                ('connection_test_passed', models.BooleanField(default=False)),
                ('browser_compatibility', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_room', to='telemedicine.telemedicinesession')),
            ],
            options={
                'db_table': 'telemedicine_virtual_waiting_room',
            },
        ),
        migrations.CreateModel(
            name='TelemedicineMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('image', 'Image'), ('file', 'File Attachment'), ('system', 'System Message'), ('prescription', 'Prescription'), ('vital_signs', 'Vital Signs')], default='text', max_length=20)),
                ('content', models.TextField(help_text='Message text content')),
                ('attachment_url', models.URLField(blank=True, help_text='URL to attached file or image')),
                ('attachment_type', models.CharField(blank=True, max_length=50)),
                ('attachment_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_by_recipient', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_clinical_note', models.BooleanField(default=False)),
                ('is_confidential', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemedicine_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telemedicine.telemedicinesession')),
            ],
            options={
                'db_table': 'telemedicine_message',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='RemoteMonitoringDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('device_type', models.CharField(choices=[('blood_pressure', 'Blood Pressure Monitor'), ('glucose_meter', 'Glucose Meter'), ('pulse_oximeter', 'Pulse Oximeter'), ('thermometer', 'Digital Thermometer'), ('weight_scale', 'Digital Scale'), ('ecg_monitor', 'ECG Monitor'), ('spirometer', 'Spirometer'), ('heart_rate_monitor', 'Heart Rate Monitor'), ('activity_tracker', 'Activity Tracker'), ('medication_dispenser', 'Smart Pill Dispenser')], max_length=30)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('connectivity_type', models.CharField(choices=[('bluetooth', 'Bluetooth'), ('wifi', 'WiFi'), ('cellular', 'Cellular'), ('usb', 'USB'), ('manual', 'Manual Entry')], max_length=20)),
                ('mac_address', models.CharField(blank=True, help_text='MAC address for network devices', max_length=17)),
                ('last_connection', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('measurement_frequency', models.CharField(choices=[('hourly', 'Every Hour'), ('daily', 'Daily'), ('twice_daily', 'Twice Daily'), ('weekly', 'Weekly'), ('on_demand', 'On Demand'), ('continuous', 'Continuous')], default='daily', max_length=20)),
                ('alert_thresholds', models.JSONField(blank=True, default=dict)),
                ('battery_level', models.PositiveIntegerField(blank=True, help_text='Battery percentage', null=True)),
                ('signal_strength', models.PositiveIntegerField(blank=True, help_text='Signal strength percentage', null=True)),
                ('last_calibration', models.DateTimeField(blank=True, null=True)),
                ('next_calibration_due', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telemedicine_remote_monitoring_device',
            },
        ),
        migrations.AddIndex(
            model_name='telemedicinesession',
            index=models.Index(fields=['patient', 'scheduled_start_time'], name='telemedicin_patient_3e626d_idx'),
        ),
        migrations.AddIndex(
            model_name='telemedicinesession',
            index=models.Index(fields=['provider', 'scheduled_start_time'], name='telemedicin_provide_e74153_idx'),
        ),
        migrations.AddIndex(
            model_name='telemedicinesession',
            index=models.Index(fields=['status'], name='telemedicin_status_32cf79_idx'),
        ),
        migrations.AddIndex(
            model_name='telemedicinesession',
            index=models.Index(fields=['session_id'], name='telemedicin_session_cb2d99_idx'),
        ),
        migrations.AddIndex(
            model_name='telemedicinemessage',
            index=models.Index(fields=['session', 'sent_at'], name='telemedicin_session_1d878c_idx'),
        ),
        migrations.AddIndex(
            model_name='remotemonitoringdevice',
            index=models.Index(fields=['patient', 'device_type'], name='telemedicin_patient_2514c8_idx'),
        ),
        migrations.AddIndex(
            model_name='remotemonitoringdevice',
            index=models.Index(fields=['is_active'], name='telemedicin_is_acti_eb2939_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='remotemonitoringdevice',
            unique_together={('patient', 'device_type', 'serial_number')},
        ),
    ]
