# Generated by Django 4.2.28 on 2026-02-16 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name or identifier of the resource', max_length=100)),
                ('resource_type', models.CharField(choices=[('bed', 'Hospital Bed'), ('icu_bed', 'ICU Bed'), ('ventilator', 'Ventilator'), ('wheelchair', 'Wheelchair'), ('monitor', 'Patient Monitor'), ('room', 'Room'), ('operating_room', 'Operating Room'), ('ambulance', 'Ambulance'), ('other', 'Other')], help_text='Type of resource', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description or notes about the resource')),
                ('location', models.CharField(blank=True, help_text='Physical location (e.g., Ward A, Room 101)', max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved'), ('out_of_service', 'Out of Service')], default='available', help_text='Current status of the resource', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units (for countable resources)')),
                ('last_maintenance', models.DateField(blank=True, help_text='Date of last maintenance', null=True)),
                ('next_maintenance', models.DateField(blank=True, help_text='Scheduled next maintenance date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital Resource',
                'verbose_name_plural': 'Hospital Resources',
                'ordering': ['resource_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_type', models.CharField(choices=[('emergency', 'Emergency'), ('scheduled', 'Scheduled'), ('transfer', 'Transfer'), ('observation', 'Observation')], default='scheduled', help_text='Type of admission', max_length=20)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of admission')),
                ('discharge_date', models.DateTimeField(blank=True, help_text='Date and time of discharge', null=True)),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged'), ('transferred', 'Transferred'), ('deceased', 'Deceased')], default='admitted', help_text='Current admission status', max_length=20)),
                ('ward', models.CharField(blank=True, help_text='Ward or department', max_length=50)),
                ('room_number', models.CharField(blank=True, help_text='Room number', max_length=20)),
                ('bed_number', models.CharField(blank=True, help_text='Bed number', max_length=20)),
                ('diagnosis', models.TextField(blank=True, help_text='Initial diagnosis')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attending_doctor', models.ForeignKey(blank=True, help_text='Primary attending physician', limit_choices_to={'role__name': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_admissions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='The admitted patient', limit_choices_to={'role__name': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admission Record',
                'verbose_name_plural': 'Admission Records',
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='StaffSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the scheduled shift')),
                ('shift', models.CharField(choices=[('morning', 'Morning (6 AM - 2 PM)'), ('afternoon', 'Afternoon (2 PM - 10 PM)'), ('night', 'Night (10 PM - 6 AM)'), ('day', 'Day Shift (8 AM - 6 PM)'), ('on_call', 'On Call')], help_text='Type of shift', max_length=20)),
                ('department', models.CharField(blank=True, help_text='Department or ward assignment', max_length=100)),
                ('start_time', models.TimeField(blank=True, help_text='Shift start time', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Shift end time', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', help_text='Schedule status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_member', models.ForeignKey(help_text='Staff member for this schedule', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Schedule',
                'verbose_name_plural': 'Staff Schedules',
                'ordering': ['date', 'shift'],
                'unique_together': {('staff_member', 'date', 'shift')},
            },
        ),
    ]
