# Generated by Django 4.2.7 on 2026-02-18 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffschedule',
            name='staff_member',
            field=models.ForeignKey(help_text='Staff member for this schedule', on_delete=django.db.models.deletion.CASCADE, related_name='staff_schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
